include:
  - board: seeeduino_xiao_ble
    shield: around_forty_tb_right rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: around_forty_tb_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
